AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

# https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/
# https://docs.aws.amazon.com/iot/latest/developerguide/thing-policy-examples.html
# https://docs.aws.amazon.com/iot/latest/developerguide/thing-policy-variables.html
# https://docs.aws.amazon.com/iot/latest/developerguide/action-resources.html

Parameters:

  CaCertificateId:
    Type: String
    Default: fbf275ba443aaffaac321fa2ed2ad79372064f18e964ce14ec9ae0c6e6915bbb

  PolicyName:
    Type: String
    Default: DonkeyCarThingPolicy

  PolicyArn:
    Type: String

  ThingTypeName:
    Type: String
    Default: Donkey

  ThingTypeArn:
    Type: String

  ThingGroupName:
    Type: String
    Default: RoboCars

  ThingGroupArn:
    Type: String

Resources:

  JitrLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: './jitr-lambda'
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - iot:*
              Resource: '*'
      Events:
        CertificateRegistration:
          Type: IoTRule
          Properties:
            Sql: !Sub "SELECT * FROM '$aws/events/certificates/registered/${CaCertificateId}'"
            AwsIotSqlVersion: '2016-03-23'
      Environment:
        Variables:
          THING_POLICY_ARN: !Ref PolicyArn
          THING_POLICY_NAME: !Ref PolicyName
          THING_TYPE_ARN: !Ref ThingTypeArn
          THING_TYPE_NAME: !Ref ThingTypeName
          THING_GROUP_ARN: !Ref ThingGroupArn
          THING_GROUP_NAME: !Ref ThingGroupName